name: Check Markdown and Text files for profanity
on:
  push:
    paths:
    - "**.md"
    - "**.mdx"
    - "**.json"
    branches:
      - main

jobs:
  setup_environment:
    runs-on: ubuntu-latest 
    name: Set up Environment
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

  get_changed_files:
    runs-on: ubuntu-latest 
    name: Get Changed Files
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

  run_profanity_check:
    needs: [setup_environment, get_changed_files]
    runs-on: ubuntu-latest 
    name: Run Profanity Check
    steps:
      - name: Install rust dependencies & build
        run: |
          cargo build --release
      - name: Run Profanity Check
        env:
          ALL_CHANGED_FILES: ${{ needs.get_changed_files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "Checking file: $file"
            cargo run --release -- "$file"
          done
