name: Check Markdown and Text files for profanity

on:
  push:
    paths:
    - "**/*.md"
    - "**/*.mdx"
    - "**/*.json"
    - "**/*.yml"
    branches:
      - published

jobs:
  check_profanity:
    runs-on: ubuntu-latest 
    name: Test Changed Files for Profanity
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
      - name: Install rust dependencies & build
        run: |
          cargo build --release
      - name: Run Profanity Check
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "Checking file: $file"
            cargo run --release -- "$file"
          done
